[project]
name = "django-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "django-tailwind>=4.2.0",
    "httpx>=0.28.1",
]

